import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: { logoImageUrl: "/favicon.ico" },
        variables: { colorPrimary: "#22C55E" },
      }}
      afterSignOutUrl="/"
    >
      <html lang="en" className={nunito.variable}>
        <body className="min-h-full flex flex-col">
          {children}
          <Toaster theme="light" richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}